Module8 task3
htmlacademy-yii/56426-task-force-1 pull request #22
Opened 2020-06-05 09:03 UTC by alfet123

2020-06-10 05:35 UTC, vlados1994 commented on frontend/controllers/AccountController.php
> +        foreach ($rows as $item) {
почитай. есть более простое решение. тебе надо asArray + еще функцию использовать вместо all

2020-06-10 05:37 UTC, vlados1994 commented on frontend/controllers/EventsController.php
> +                'task_name' => $event->task->name,
аналогично предыдущему. можно еще и псевдонимы делать в запросе

2020-06-10 05:39 UTC, vlados1994 commented on frontend/controllers/EventsController.php
> +        $events = Event::find()->where(['user_id' => Yii::$app->user->getId(), 'is_viewed' => false])->all();
быстрее это один запросом сделать, без цикла

2020-06-10 05:39 UTC, vlados1994 commented on frontend/controllers/EventsController.php
> +        return true;
смысла не имеет возвращать, в случае ошибки он кинет исключение, а в случае успеха - 200

2020-06-10 05:40 UTC, vlados1994 commented on frontend/controllers/EventsController.php
> +        return json_encode($data, JSON_UNESCAPED_UNICODE);
у ии2 что-то свое есть для возвращения жсон, чтобы лишний раз этот encode не писать

2020-06-10 05:42 UTC, vlados1994 commented on frontend/controllers/ListController.php
> +        if (User::getRole() == UserRole::CUSTOMER) {
имхо, тернарный оператор тут нормально бы смотрелся

2020-06-10 05:45 UTC, vlados1994 commented on frontend/models/UserAccountForm.php
> +        $this->profile->city_id = $this->city;
100% такую запись можно заменить конструкцией на 1-3 строки

2020-06-10 05:45 UTC, vlados1994 commented on frontend/models/UserAccountForm.php
> +        $this->settings->new_message = (int)$this->new_message;
и эту. имена-то почти у всех одинаковые. можно тупо через цикл

2020-06-10 05:47 UTC, vlados1994 commented on frontend/models/UserAccountForm.php
> +        $skills = is_array($this->skills) ? $this->skills : [];
вроде бы ничего, но поведение какое-то не очевидное
     $skills = is_array($this->skills) ? $this->skills : [];

2020-06-10 05:48 UTC, vlados1994 commented on frontend/models/UserAccountForm.php
> +        foreach ($skills as $skillNumber) {
вот это костыль. тебе надо это через связи делать

2020-12-14 18:50 UTC, runtothefather requested changes
комменты которые были оставлены раньше + какие-то новые

2020-12-14 18:50 UTC, runtothefather commented on frontend/controllers/AccountController.php
> +        foreach ($rows as $item) {
array_column или array_map + arrow function

2020-12-14 18:50 UTC, runtothefather commented on frontend/controllers/EventsController.php
> +        $events = Event::find()->where(['user_id' => Yii::$app->user->getId(), 'is_viewed' => false])->all();
просто update написать нужно

2020-12-14 18:50 UTC, runtothefather commented on frontend/controllers/ListController.php
> +        if (User::getRole() == UserRole::CUSTOMER) {
+ сравнения все должны быть строгими (===)

2020-12-14 18:50 UTC, runtothefather commented on frontend/models/UserAccountForm.php
> +        $this->task_actions = (boolean)$this->settings->task_actions;
просто (bool)

2020-12-14 18:50 UTC, runtothefather commented on frontend/models/UserAccountForm.php
> +        foreach ($this->user->skills as $skill) {
попробуй array_column

2020-12-15 19:00 UTC, runtothefather approved these changes

2020-12-15 19:00 UTC, runtothefather commented on frontend/controllers/EventsController.php
> +        $events = Event::find()->where(['user_id' => Yii::$app->user->getId(), 'is_viewed' => false])->all();
тут я имел в виду не доставать объекты а просто в базу апдейт нужный сделать, ладно

2020-12-15 19:00 UTC, merged