Module9 task2
htmlacademy-yii/56426-task-force-1 pull request #24
Opened 2021-01-21 13:15 UTC by alfet123

2021-01-21 19:26 UTC, runtothefather requested changes

2021-01-21 19:26 UTC, runtothefather commented on frontend/config/main.php
> +            'hostname' => 'localhost',
такое надо выносить в файл который не комитится по 2 причинам, 1-я безопасность, 2-я как сделать разные настройки локально-продакшн?

2021-01-21 19:26 UTC, runtothefather commented on frontend/models/TaskCreateForm.php
> +        if ($value_long && $value_lat) {
какие значения тут ожидаются bool, int ..etc? необходимы более точные сравнения (null !== $a)

2021-01-21 19:26 UTC, runtothefather commented on frontend/models/TaskCreateForm.php
> +            $response_data = json_decode($content, true);
названия переменных снейк кейсом везде? я смотрю что ключи у массивов нет

2021-01-22 19:07 UTC, alfet123 commented on frontend/models/TaskCreateForm.php
> +            $response_data = json_decode($content, true);
Я использую подчеркивание в названии переменных. Ключи в массивах другие, потому что получены из внешних источников.

2021-01-27 08:48 UTC, runtothefather approved these changes

2021-01-27 08:48 UTC, merged